### Get Products
GET http://localhost:8080/api/products

### Get Products by it's Category
GET http://localhost:8080/api/product-category/3/products

### Get Products by keyword
GET http://localhost:8080/api/products/search/queryByKeyword?name=express&categoryId=2&page=0&size=20

### Post Product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "sku": "BOOK-TECH-1004",
  "name": "The Go Programming Language: A to Z",
  "description": "Learn Go",
  "unitPrice": 24.99
}

### Delete Product
DELETE http://localhost:8080/api/products/1